### ISSUE TITLE
Stay alwaysOnTop even above fullscreen mode

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#1]
Windows attempts to hide overlays on fullscreen mode, requiring windowed fullscreen to work with CrossOver.

**Comment by marcmascarell** [comment]
This is indeed a big issue for some apps... Give this a look https://github.com/hiitiger/gelectron

**Comment by lacymorrow** [comment]
gelectron looks very cool and very similar to what I'm designing, although I'm attempting to make the 'injection' invisible on load and keep this app cross-platform

**Comment by lacymorrow** [comment]
This may actually be near-impossible for Electron apps without some sort of injection method, and then may be detected by anti-cheat systems. Unless someone wants to investigate using native modules to handle this, it will be a `wontfix`.

Related: #26

**Comment by benjaminaudet** [comment]
Hi!
Did you already try this : https://github.com/electron/electron/issues/10078#issuecomment-331581160

**Comment by lacymorrow** [comment]
This is fixed in the latest version 🙂

**Comment by benjaminaudet** [comment]
I am currently using the 1.0.3 and it's not working with the fullscreen of the game Rust :(

**Comment by lacymorrow** [comment]
@benjaminaudet What OS?
Try the latest version as I've made a few updates

**Comment by benjaminaudet** [comment]
Windows 10
Still not working with the version 1.0.8 (I built it myself)

**Comment by lacymorrow** [comment]
Yep, unfortunately this is a limitation of Electron, GPU-accelerated programs (especially Vulkan), and probably anti-cheat systems. It sucks but until someone can offer me a valid cross-platform method of getting above fullscreen windows, I don't plan to ever support it

(because I am not going to write and support a native extension myself)

**Comment by ro31337** [comment]
> valid cross-platform method

There can't be valid cross-platform method because of specifics of the problem. It's better to start supporting it for one platform with "not implemented" fallback for other platforms.

**Comment by KeroOs** [comment]
There is a problem with the program that when I try to lock the crossover the background of the program keeps showing in Windows 7 Ultimate
I hope to solve the problem.

**Comment by lacymorrow** [comment]
Fortnite has updated the way they display as well and is no longer showing in windowed-fullscreen mode either :/

**Comment by AVITECHNO** [comment]
I tried to use it for Halo Masterchief collection, but is not working when playing at Fullscreen
